version: '3.3'
services:
  traefik:
    command:
      - --providers.docker
      - --providers.docker.swarmmode
      - --providers.docker.watch
      - --providers.docker.exposedbydefault=false
#      - --providers.docker.constraints="Label(`tag`, `${TRAEFIK_PUBLIC_NETWORK}`)"
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.default.acme.httpchallenge=true
      - --certificatesresolvers.default.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.default.acme.email=${EMAIL?Variable EMAIL not set}
      - --certificatesresolvers.default.acme.storage=/acme.json
#      - --certificatesresolvers.default.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --log.level=INFO
      - --accessLog
      - --api
      - --api.dashboard