version: '3.3'
services:
  traefik:
    deploy:
      replicas: ${TRAEFIK_REPLICAS:-3}
      placement:
        constraints:
          - node.role == manager
        preferences:
          - spread: node.id
  backend:
    deploy:
      replicas: ${BACKEND_REPLICAS:-3}

  frontend:
    deploy:
      replicas: ${FRONTEND_REPLICAS:-3}