version: '3.3'
services:
  traefik:
    networks:
      - ${TRAEFIK_PUBLIC_NETWORK}
      - default

  backend:
    networks:
      - ${TRAEFIK_PUBLIC_NETWORK}
      - default

  frontend:
    networks:
      - ${TRAEFIK_PUBLIC_NETWORK}
      - default

networks:
  traefik-public:
    external: true