version: '3.3'
services:
  traefik:
    labels:
      - traefik.http.routers.proxy.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.proxy.entrypoints=web
      - traefik.enable=true

  backend:
    labels:
      - traefik.http.routers.backend.rule=Host(`${DOMAIN}`) && PathPrefix(`/api`)
      - traefik.http.routers.backend.entrypoints=web
      - traefik.enable=true
      - traefik.tags=${TRAEFIK_TAG}

  frontend:
    labels:
      - traefik.http.routers.frontend.rule=Host(`${DOMAIN}`) && PathPrefix(`/`)
      - traefik.http.routers.frontend.entrypoints=web
      - traefik.enable=true
      - traefik.tags=${TRAEFIK_TAG}