version: '3.3'
services:
  traefik:
    command:
      - --entrypoints.web.address=:80
      - --providers.docker
      - --providers.docker.watch
      - --providers.docker.exposedbydefault=false
      - --log.level=DEBUG
      - --accessLog
      - --api.insecure # Don't do that in production

  backend:
#    command: bash -c "while true; do sleep 1; done"  # Infinite loop to keep container live doing nothing
#    command: bash -c "uvicorn enkefalos_api.main:app --reload --host=0.0.0.0 --port=80"