version: "3.3"
services:
    backend:
        build: .
        image: pycloud_api:latest
        ports:
            - 80:80
        env_file:
            - .env
        environment:
            - APP_MODULE=pycloud_api.main:app
        volumes:
            - .:/app
        command: bash -c "uvicorn pycloud_api.main:app --reload --host=0.0.0.0 --port=80"
#        command: bash -c "while true; do sleep 1; done"  # Infinite loop to keep container live doing nothing
